### ISSUE TITLE
Getting runtime issue on Mac

### ISSUE THREAD

**Issue by bill-lu** [bill-lu/solidity-bootcamp-weekendprojects#12]
Having issue running the operate scripts (week2 project) on Mac:

Expected Behavior:

The script will perform the following actions without issue

1. Deploy token contract.
2. Mint token
3. Delegate token.
4. Deploy custom ballot contract
5. Vote for proposal
6. Getting the winner.

Actual Behavior:
The scripts run without issue for the first 5 steps. But fails on step 6 (most of the time) with following message.
`getting winner name
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.4)
    at Logger.makeError (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at /Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:631:24
    at Array.forEach (<anonymous>)
    at /Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:613:33
    at step (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
    at Object.next (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
    at step (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
    at Object.next (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
    at fulfilled (/Users/billlu/Projects/Blockchains/solidity-bootcamp/solidity-bootcamp-weekendprojects/Week2/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION'
}`

Also, if just repeat step 5 and 6 (uses the contract address of previous deployed), then it runs without issue.

**Comment by bill-lu** [comment]
Wrong contract address?
https://ethereum.stackexchange.com/questions/127271/ethers-contract-call-for-value-of-state-variable-reverts-with-missing-revert-da

Added log to ensure the right address is used:
`Voting for proposal 1, using ballot contract at 0xB5acf90808a6C5dF402870C302A6B31031b06358
Voted for proposal 1 with 20 Token 0x95e28b882ef70974f23ed5a771a47f410d3214317a844f9a157a0c7eb5c05dad
getting winner name -- using ballot contract at 0xB5acf90808a6C5dF402870C302A6B31031b06358
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.4)
`

**Comment by bill-lu** [comment]
Some people have the similar issue:
https://stackoverflow.com/questions/72201766/error-missing-revert-data-in-call-exception-on-tokenofownerbyindex-and-tokenbyi

**Comment by bill-lu** [comment]
The following change seems to fix the issue:
change 
`const winnerName = await ballotContract.winnerName();`
to
`ballotContract.winnerName().then(
    (name) => {
      console.log(`winner is: ${ethers.utils.parseBytes32String(name)}`);
    }
  )`

**Comment by MatheusDaros** [comment]
@bill-lu thanks for sharing these details.
Since `winnerName` is a read function, it has only one way to fail. When doing `proposals[winningProposal()]` it may give an error if trying to read a position not present in the proposals array. So, unless you have changed the contract logic, this is **highly unlikely** to be the actual problem there.
Perhaps are you missing some previous steps? Perhaps the transaction before that is failing? Have you tried to write a script to only call this function? Then we could isolate the error, maybe.

**Comment by bill-lu** [comment]
@MatheusDaros thanks for looking into this issue.
This is pretty odd. We reviewed and contract (no modification) and the scripts and couldn't find any issue. 
When using `const winnerName = await ballotContract.winnerName();`, it failed 100% at the last step (getting the winner).
When changing to `ballotContract.winnerName().then( (name) => {...})`, most of the time, it runs without issue.
Really don't know why though.

**Comment by MatheusDaros** [comment]
Very odd indeed.
This problem you are facing could be related to something about the async logic. In fact those problems do happen some time, just not that often.
What is most uncommon about this situation is not the error itself, by what I see. What is really strange is that this `ballotContract.winnerName().then( (name) => {...})` structure does exactly the same thing as awaiting, since you are not doing anything else in the meantime, if I have checked the correct files, so it shouldn't be fixing. I would expect for both cases to fail, or both cases to work, to be honest.
I suggest we go back to this in the future and try to debug line by line inside a test environment.
